name = "SignalAnalysis"
uuid = "df1fea92-c066-49dd-8b36-eace3378ea47"
authors = ["Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.4.1"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaArrays = "36b8f3f0-b776-11e8-061f-1f20094e1fc8"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SignalBase = "00c44e92-20f5-44bc-8f45-a1dcef76ba38"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[compat]
DSP = "0.6, 0.7"
Distributions = "0.23, 0.24, 0.25"
DocStringExtensions = "0.8,0.9"
FFTW = "1"
MetaArrays = "0.2"
PaddedViews = "0.5"
Requires = "1"
SignalBase = "0.1"
WAV = "1"
julia = "1"
